overrides:
  ansi-html@<0.0.8: '>=0.0.8'
  braces@<3.0.3: '>=3.0.3'
  browserslist@>=4.0.0 <4.16.5: '>=4.16.5'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  ejs@<3.1.10: '>=3.1.10'
  ejs@<3.1.7: '>=3.1.7'
  eslint@<9.26.0: '>=9.26.0'
  http-proxy-middleware@<2.0.7: '>=2.0.7'
  immer@>=7.0.0 <9.0.6: '>=9.0.6'
  loader-utils@>=2.0.0 <2.0.3: '>=2.0.3'
  loader-utils@>=2.0.0 <2.0.4: '>=2.0.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<3.0.5: '>=3.0.5'
  node-forge@<1.0.0: '>=1.0.0'
  node-forge@<1.3.0: '>=1.3.0'
  node-forge@<1.3.2: '>=1.3.2'
  nth-check@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  rollup@<2.79.2: '>=2.79.2'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  shell-quote@>=1.6.3 <=1.7.2: '>=1.7.3'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
